### PR TITLE
Feat/crime recorder

### LINKED ISSUE #18: Crime recorder
- [ ] Implement user friendly error handling and success messages components on every page
- [ ] modify modals to blur the overlaying page 
- [ ] the video/image cards on smaller screens looks weird
Screenshot from 2024-10-18 10-58-25

- [ ] camera remains active after taking pictures and routing to the video pages

### PR DESCRIPTION
**Pull request by Ayoazeez26**
Fixes #18

### CODE REVIEW

**Review by faytey — CHANGES_REQUESTED** [review]
Kindly resolve the conflicts on this file, thanks

**Review by faytey — CHANGES_REQUESTED** [review]
kindly add a picture or video showing your fix to this issue from your local deployment

**Review by faytey — CHANGES_REQUESTED** [review]
The modal should only pop up when an upload has been successfully made, not together on the recorder and obstructing the view

**Comment by Ayoazeez26** [comment]
Yeah I saw it after resolving the conflicts, I am resolving it now

**Comment by Ayoazeez26** [comment]
image
image
image
Screenshot 2024-11-01 at 15 36 32

@faytey I am unable to add the screenshot of the list of recorded photos and videos that I worked on it's mobile responsiveness because I get an empty state after successfully uploading photos

**Review by faytey — APPROVED** [review]

**Pull request merged**
