### PR TITLE
fixes #22

### LINKED ISSUE #22: Crime recorder UI fixes
- [ ] Fix record button and switch camera button
- [ ] Animate switch camera button
- [ ] Start and stop recording buttons should have active state
- [ ] Fix body scroll into footer 
Screenshot 2024-10-23 at 09 44 10

### PR DESCRIPTION
**Pull request by SudiptaPaul-31**
Fixes #22  - Crime recorder UI 

 ✅Fix record button and switch camera button
 ✅Animate switch camera button
 ✅Start and stop recording buttons should have active state
 ✅Fix body scroll into footer

### CODE REVIEW

**Review by Goodness5 — CHANGES_REQUESTED** [review]
- [ ] The countdown/name your video modal should be a blurred overlay
image

- [ ] The font size (video name tag) for each video on the cards are too small. 
image

- [ ] No loading state for each process
- [ ] The modals are overriding each other

there is a loading component already built incorporate it in the process you'll find it in the components folder

also please refer to figma design here: https://www.figma.com/design/3nZ7dFPCVz4fdnfP5ZGlL6/Custos-Diretriz?t=CRpFrJAHqeJbf8x2-0

**Comment by Goodness5** [comment]
> * [ ]  The countdown/name your video modal should be a blurred overlay
>   image
> * [ ]  The font size (video name tag) for each video on the cards are too small.
>   image
> * [ ]  No loading state for each process
> * [ ]  The modals are overriding each other
> 
> there is a loading component already built incorporate it in the process you'll find it in the components folder
> 
> also please refer to figma design here: https://www.figma.com/design/3nZ7dFPCVz4fdnfP5ZGlL6/Custos-Diretriz?t=CRpFrJAHqeJbf8x2-0

@SudiptaPaul-31

**Comment by SudiptaPaul-31** [comment]
@Goodness5 I am facing an issue with the loading component present inside the components folder where it is not rendering properly everytime I am doing setLoading(true) its not working can you give some more details
Moreover the loading.jsx component is appearing like this 
image
Its appearing like this the green check icon is not appearing

**Comment by Goodness5** [comment]
@SudiptaPaul-31 you can check out the layout file for more context it looks like  also the success component is what you're trying to load and for some reasons it's in the agreement/components directory 
also you can check the logs maybe there's a 404 for the icon which might be due to wrong links

**Comment by SudiptaPaul-31** [comment]
@Goodness5 can you explain more about this issue The font size (video name tag) for each video on the cards are too small. I mean where is the file present and what does it do?

**Comment by Goodness5** [comment]
@SudiptaPaul-31 please run build locally and ensure it builds successfully before pushing to prevent failing deployments

**Comment by SudiptaPaul-31** [comment]
@Goodness5 I tried several times but Vercel deployment failed last time it was alright but this time it's not checked it using yarn build there was no such error but deployment fails several times. Could you please check this problem of failed deployment.

**Comment by Goodness5** [comment]
@SudiptaPaul-31 
image

**Review by mercykolapo — COMMENTED** [review]
Well done ✅ 

Screenshot_2024-10-26-11-38-55-844_com android chrome
On
Screenshot_2024-10-26-11-39-47-229_com android chrome
 Mobile, the modals are so slim and small

**Comment by SudiptaPaul-31** [comment]
@Goodness5 can you please check that I had already made this changes previously

✅The countdown/name your video modal should be a blurred overlay
✅The font size (video name tag) for each video on the cards are too small.
✅No loading state for each process
✅The modals are overriding each other

**Comment by SudiptaPaul-31** [comment]
@Goodness5 can you please check that I had already made this changes previously

- [X] The countdown/name your video modal should be a blurred overlay
- [X] The font size (video name tag) for each video on the cards are too small.
- [X] No loading state for each process
- [X] The modals are overriding each other

**Comment by SudiptaPaul-31** [comment]
@Goodness5 Please have a look, I solved the problem of having modals small on mobile by making it responsive for different devices.

**Comment by Goodness5** [comment]
> @Goodness5 Please have a look, I solved the problem of having modals small on mobile by making it responsive for different devices.

nice job i can see you've fixed the modals for recording and saving the videos
it seems you missed the success modal's mobile view i tested on mobile and the texts seems to be overflowing 
Screenshot from 2024-10-27 12-20-50 this occurs mostly on devices with widths smaller than 650px also the homepage to display the recorded media has the same issue 
image

the time stamp texts is overflowing due to the no-wrap class i think can you fix that and test across small devices so i can merge this PR 

thanks for your work

**Comment by SudiptaPaul-31** [comment]
@Goodness5  can you please tell me that in which route this page can be found " the homepage to display the recorded media has the same issue"

**Review by custosDiretriz — APPROVED** [review]

**Pull request merged**
