### PR TITLE
fix: fixed the search functionality, implemented navbar and sidebar UI

### LINKED ISSUE #24: General Dapp Fixes
- [ ] Make search input on the nav bar work as should be
- [ ] Side bar,Nav bar, connect wallet fixes to align with figma design here
https://www.figma.com/design/3nZ7dFPCVz4fdnfP5ZGlL6/Custos-Diretriz?node-id=0-1&node-type=canvas&t=MFsQFI1P8Haph2Wl-0

### PR DESCRIPTION
**Pull request by PoulavBhowmick03**
fixes #24

### CODE REVIEW

**Comment by PoulavBhowmick03** [comment]
@Khauthymo  PTAL

**Review by Goodness5 — CHANGES_REQUESTED** [review]
Minimise navbar feature (check Figma)
Change button colour and sidepane colour to follow design system. Add hover effect to the button. See Figma prototype: https://www.figma.com/proto/3nZ7dFPCVz4fdnfP5ZGlL6/Custos-Diretriz?page-id=0%3A1&node-id=1135-3539&node-type=frame&viewport=616%2C453%2C0.04&t=9yAgUNu2pGDDFWlf-1&scaling=scale-down-width&content-scaling=fixed&starting-point-node-id=1135%3A3539&show-proto-sidebar=1.
Take out connect wallet from the side navbar on desktop view

please check figma design here: https://www.figma.com/design/3nZ7dFPCVz4fdnfP5ZGlL6/Custos-Diretriz?node-id=645-2250&node-type=frame&t=SZrQbCkWDo6zOuvO-0

**Comment by Goodness5** [comment]
> PTAL



> Minimise navbar feature (check Figma) Change button colour and sidepane colour to follow design system. Add hover effect to the button. See Figma prototype: https://www.figma.com/proto/3nZ7dFPCVz4fdnfP5ZGlL6/Custos-Diretriz?page-id=0%3A1&node-id=1135-3539&node-type=frame&viewport=616%2C453%2C0.04&t=9yAgUNu2pGDDFWlf-1&scaling=scale-down-width&content-scaling=fixed&starting-point-node-id=1135%3A3539&show-proto-sidebar=1. Take out connect wallet from the side navbar
> 
> please check figma design here: https://www.figma.com/design/3nZ7dFPCVz4fdnfP5ZGlL6/Custos-Diretriz?node-id=645-2250&node-type=frame&t=SZrQbCkWDo6zOuvO-0

@PoulavBhowmick03

**Comment by PoulavBhowmick03** [comment]
@Goodness5 can you please tell me which button's hover are you referring to? there is a button on the crime recorder page but that has an image of "Start Recording"

**Comment by PoulavBhowmick03** [comment]
I have done the other changes, I just need to add the hover to the button you mentioned  and change it's color

**Comment by Goodness5** [comment]
> I have done the other changes, I just need to add the hover to the button you mentioned and change it's color

@PoulavBhowmick03 nice job 

the only changes requested were the button's state (connect wallet button to be precise ) it has a border gradient and the sidepane's colour i can see you fixed that by the way the extra links added to d sidebar previously were nice obviously
image
you can see the buttons colour scheme on figma it's border radient and on hover it changes to blue
image
just the connect button and you can leave those extra links too theyre nice

**Comment by PoulavBhowmick03** [comment]
got it, thanks. onto it

**Comment by PoulavBhowmick03** [comment]
@Goodness5  Done, PTAL
here is the video showing the changes


https://github.com/user-attachments/assets/a06c2b70-6cf3-4086-9e65-61ddbf535192

**Review by Goodness5 — APPROVED** [review]
perfect @PoulavBhowmick03 nice job  i'll be merging this now
you can create issues if you notice some other issues which you'll like to attend to
thanks

**Comment by PoulavBhowmick03** [comment]
@Goodness5 Thanks! Alrighty, will look if there are more issues to be made or worked on, and can I contact you through tg?

**Comment by Goodness5** [comment]
-

> @Goodness5 Thanks! Alrighty, will look if there are more issues to be made or worked on, and can I contact you through tg?

yes you can i'll respond thanks

**Pull request merged**
